apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: spark-operator
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: spark-operator
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: spark-operator
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: manager
        image: controller:latest
        args:
          - controller
          - start
          - --namespaces=""
          - --controller-threads=10
          - --enable-ui-service=true
          - --leader-election=true
          - --leader-election-lock-name=spark-operator-lock
          - --leader-election-lock-namespace=$(POD_NAMESPACE)
          - --enable-metrics=true
          - --metrics-bind-address=:8080
          - --metrics-endpoint=/metrics
          - --metrics-labels=app_type
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 750m
            memory: 1.5Gi
          requests:
            cpu: 10m
            memory: 64Mi
        imagePullPolicy: Always
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
