apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server
  namespace: system
  labels:
    control-plane: webhook-server
    app.kubernetes.io/name: spark-operator
spec:
  selector:
    matchLabels:
      control-plane: webhook-server
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: webhook-server
      labels:
        control-plane: webhook-server
        app.kubernetes.io/name: spark-operator
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: webhook-server
          image: controller:latest
          args:
            - webhook
            - start
            - --namespaces=""
            - --webhook-cert-dir=/tmp/k8s-webhook-server/serving-certs
            - --webhook-svc-name=spark-operator-webhook-service
            - --webhook-svc-namespace=$(POD_NAMESPACE)
            - --webhook-port=9443
            - --mutating-webhook-name=spark-operator-mutating-webhook
            - --validating-webhook-name=spark-operator-validating-webhook
            - --enable-resource-quota-enforcement=true
            - --leader-election=true
            - --leader-election-lock-name=spark-operator-webhook-lock
            - --leader-election-lock-namespace=$(POD_NAMESPACE)
            - --enable-metrics=true
            - --metrics-bind-address=:8080
            - --metrics-endpoint=/metrics
            - --metrics-labels=app_type
          ports:
            - containerPort: 9443
              name: webhook
              protocol: TCP
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          imagePullPolicy: Always
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
